# Usamos una imagen base de Go
FROM golang:1.19 AS builder

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos todos los archivos del proyecto al contenedor
COPY . .

# Instalamos las dependencias
RUN go mod tidy

# Compilamos el proyecto
RUN go build -o main .

# Etapa final: creamos una imagen mínima para ejecutar el binario
FROM alpine:latest

# Establecemos el directorio de trabajo dentro del contenedor final
WORKDIR /root/

# Copiamos el binario compilado desde la etapa anterior
COPY --from=builder /app/main .

# Comando para ejecutar la aplicación
CMD ["./main"]